FROM .azurecr.us/actions-runner-base:2.322.0 AS base
COPY openssl.cnf /etc/ssl/openssl.cnf
COPY settings.xml /home/runner/.m2/settings.xml
RUN sudo chown -R runner:runner .m2

FROM base AS core
COPY osk-certificates.crt /usr/local/share/ca-certificates/
RUN sudo awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "/usr/local/share/ca-certificates/cert." c ".crt"}' < /usr/local/share/ca-certificates/osk-certificates.crt \
    && sudo rm /usr/local/share/ca-certificates/osk-certificates.crt \
    && sudo update-ca-certificates
RUN sudo apt-get update \
    && sudo apt-get install -y --no-install-recommends \
        jq \
        zip \
        git \
        wget \
        curl \
        gnupg \
        unzip \
        lsb-release \
        apt-transport-https \
        software-properties-common

FROM core AS provisioner
RUN sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq \
    && sudo mkdir -p -m 755 /etc/apt/keyrings && sudo curl -sLS https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/microsoft.gpg \
    && AZ_DIST=$(lsb_release -cs) \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_DIST main" | sudo tee /etc/apt/sources.list.d/azure-cli.list > /dev/null \
    && sudo curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg \
    && sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg \
    && echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null \
    && sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list \
    && sudo curl https://baltocdn.com/helm/signing.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list \
    && sudo curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - \
    && sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc > /dev/null \
    && sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list)" \
    && wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb \
    && sudo apt-get update \
    && sudo apt-get install -y --no-install-recommends \
        gh \
        azure-cli \
        kubectl \
        openjdk-17-jdk \
        openjdk-17-jre \
        openjdk-21-jdk \
        openjdk-21-jre \
        nodejs \
        helm \
        sqlcmd \
        dotnet-sdk-8.0 \
        libgtk2.0-0 \
        libgtk-3-0 \
        libgbm-dev \
        libnotify-dev \
        libxss1 \        
        xvfb \
    && sudo npm install --global yarn \
    && sudo npm install --global vercel \
    && MAVEN_VERSION=3.9.6 \
    && sudo mkdir -p /usr/share/maven /usr/share/maven/ref \
    && sudo curl -fsSL -o /tmp/apache-maven.tar.gz https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && sudo tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
    && sudo rm -f /tmp/apache-maven.tar.gz \
    && [ -L /usr/bin/mvn ] && sudo rm /usr/bin/mvn || true \
    && sudo ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
    && if ! sudo keytool -list -keystore $(dirname $(dirname $(readlink -f $(which javac))))/lib/security/cacerts -storepass changeit -alias startssl > /dev/null 2>&1; then \
           sudo keytool -importcert -alias startssl -keystore $(dirname $(dirname $(readlink -f $(which javac))))/lib/security/cacerts -storepass changeit -file /etc/ssl/certs/ca-certificates.crt --noprompt; \
       fi \    
    && sudo curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64  \
    && sudo install skaffold /usr/local/bin/ \
    && curl "https://aka.ms/sqlpackage-linux" -4 -sL -o '/tmp/sqlpackage.zip' \
    && mkdir -p $HOME/sqlpackage && unzip -o /tmp/sqlpackage.zip -d $HOME/sqlpackage && chmod a+x $HOME/sqlpackage/sqlpackage && sudo ln -sf $HOME/sqlpackage/sqlpackage /usr/local/bin && rm /tmp/sqlpackage.zip \
    && az cloud set --name AzureUSGovernment

FROM provisioner AS runner
RUN sudo rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
