name: Build and Deploy - Production
on:
  workflow_dispatch

jobs:
  set_success_fail_workflow_name: 
    runs-on: ubuntu-latest   
    steps:
    - name: Set workflow name for slack message
      id: set-slack-workflow-name
      run: |
        echo $VAR_ONE                           
                       
