name: Example Workflow

on: [push]

jobs:
  slack_update_result_cancelled:
    if: ${{ always() }}    
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: ${{ cancelled() && 'true' || 'false' }} 
    secrets: inherit
