name: Build and Deploy - Production
on:    
  workflow_dispatch:
    inputs:
      import-destination:
        description: 'Some input'
        required: true
        type: choice
        options: 
          - 'DEV'          
          - 'PROD'
          - 'TEST'        

jobs:
  call-reusable-job: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.import-destination }}  
    steps:    
    - name: Create github app token 
      run: echo 'hello world'
      
