name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    environment: stg    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag from ghcr.io
        id: get-latest-tag
        env:
          CURRENT_ENVIRONMENT: ${{ job.environment }}  # Set the environment variable        
        run: |          
          json_file="mydata.json"
          # Check if the JSON file exists
          if [[ ! -f "$json_file" ]]; then
              echo "File $json_file does not exist."
              exit 1
          fi
          current_environment="stg"
          jq -c '.[]' "$json_file" | while read -r item; do
              {
                image_source_repository=$(echo "$item" | jq -r '.image_source_repository')
                tag_extractor_string=$(echo "$item" | jq -r '.tag_extractor_string')
                acr_image_name=$(echo "$item" | jq -r '.acr_image_name')
                is_docker_image=$(echo "$item" | jq -r '.is_docker_image')
                docker_file_path=$(echo "$item" | jq -r '.docker_file_path')
                docker_substitution_source=$(echo "$item" | jq -r '.docker_substitution_source')
                docker_substitution_target=$(echo "$item" | jq -r '.docker_substitution_target')
                acr_base_image_import_source=$(echo "$item" | jq -r '.acr_base_image_import_source')
                docker_file_folder_path=$(echo "$item" | jq -r '.docker_file_folder_path')
                base_image_name=$(echo "$item" | jq -r '.base_image_name')
                image_tag_prefix=$(echo "$item" | jq -r '.image_tag_prefix')
                applicable_environment=$(echo "$item" | jq -r '.applicable_environment | @csv')
                
                # Check if the current environment is in the applicable environments
                if [[ ! ",$applicable_environment," == *",$current_environment,"* ]]; then
                  echo "Skipping $acr_image_name as it is not applicable for the $current_environment environment."
                  continue
                fi
                
                echo "------Processing: $acr_image_name ------"
              } || {
                  echo "An error occurred while processing: Error: $?"
                  continue
              }
          done                
               
