name: Build and Deploy - Production
on:    
  workflow_dispatch:
    inputs:
      import_destination:
        description: 'Some input'
        required: true
        type: integer

jobs:
  call-reusable-job: 
    runs-on: macos-latest
    steps:                
    - name: Test env
      env:
        import_destination: "${{ inputs.import_destination }}"
      run: |
       echo ${import_destination}
      
