name: Schema update automation

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true  
    
jobs:
  generate_delta_script:
    strategy:
      matrix:
        environment: ['dev', 'qa', 'prod']
    continue-on-error: true
    if: (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Generate delta script
        run: |
          if [[ ${{ matrix.environment }} == 'dev' ]]; then
            exit 1
          fi
          echo "${{ vars.DB_SERVER }}"
          echo "Hello World" >schema-changes.sql

          echo "${{ github.event_name }}"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        id: upload-artifact
        with:
          name: delta-script-${{ matrix.environment }}
          path: schema-changes.sql

      - name: Post artifact link as comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactUrl = `${{ steps.upload-artifact.outputs.artifact-url }}`;
            const commentBody = `The delta script for environment ${{ matrix.environment }}: [schema-changes.sql](${artifactUrl}).`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  publish_stg:
      needs: generate_delta_script
      if: (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch') && always()
      uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
      with:
        environment: approval-dev       
  
  publish_dev:
    needs: publish_stg
    if: (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch') && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev   

  publish_qa:
    needs: publish_dev
    if: (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch') && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev   

  publish_prd:
    needs: publish_qa
    if: (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch') && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev    
