name: Build and Deploy - Production
on:
  #schedule:
    #- cron: '*/6 * * * *'
  
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: choice
        options: 
          - 'ubuntu-latest'
      some:
        description: 'Some input'
        required: true
        type: choice
        options: 
          - 'dev'          
          - 'test'
          - 'prod'

jobs:
  test2: 
    strategy: 
      matrix:
        runner: [ubuntu-latest, macos-latest]
    runs-on: ["${{ matrix.runner }}"]
    env:
      myenvironment: ${{ if eq(inputs.myinput, 'dev') }}development${{ else if eq(inputs.myinput, 'test') }}stage${{ else }}production${{ endif }}    
    steps:
      - name: print hello world        
        run: echo "myenvironment is $myenvironment"
      
     

       
