name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag from ghcr.io
        id: get-latest-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tags=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://ghcr.io/v2/actions/gha-runner-scale-set-controller/tags/list | jq -r '.tags[]')
          latest_tag=$(echo "$tags" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Use latest tag
        run: echo "The latest tag is ${{ steps.get-latest-tag.outputs.latest_tag }}"
