name: Build and Deploy - Production

on:
  schedule:
    - cron: '*/6 * * * *'
  
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: choice
        options: 
          - 'ubuntu-latest'

env:
  DEFAULT_SOURCE: 'macos-latest'  

jobs:
  test2:
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with: 
      some_input: ${{ inputs.some_input || $DEFAULT_SOURCE }}
      
     

       
