name: Build and Deploy - Production
on:    
  push    
jobs:
  call-reusable-job: 
    runs-on: macos-latest
    steps:                
    - name: Test env
      env:
        import_destination: "Hello"
      run: |
       echo ${import_destination}
      
