name: Deploy 
on: 
  workflow_dispatch:
    inputs:
      nx-Apps:
        required: false
        type: choice
        description: Select the App
        options:
          - 'nx-id'
          - 'nx-ole'
          - 'nx-jlg'

jobs:
  delete-and-create-dev-branch:
    runs-on: ubuntu-latest      
    steps:
     
      
      - name: Delete current DEV branch
        run: |
          echo "Hello ${{ inputs.nx-Apps }}"
