name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    strategy:
          matrix:
            profile_environment: ['dev', 'test', 'prod']
          max-parallel: 1
    environment: ${{ matrix.profile_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Set latest_tag variable 1
        id: my_id
        #env: 
          #latest_tag: "44.66.6"
        run: |          
          echo "latest_tag=2.319.1" >> $GITHUB_ENV
          latest_tag="2.44.4"
          #yq eval '(.images[] | select(.name == "ghcr.io/actions/gha-runner-scale-set-controller") | .newTag) =  env(latest_tag)' -i mynewfile.yml
          yq eval "(.images[] | select(.name == "ghcr.io/actions/gha-runner-scale-set-controller") | .newTag) =  "\${latest_tag}\"" -i mynewfile.yml
          cat  mynewfile.yml
        shell: bash
