name: Schema update automation

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]
    
jobs:
  generate_delta_script:
    strategy:
      matrix:
        environment: ['dev', 'qa', 'prod']  
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Generate delta script
        run: |
          echo "${{ vars.DB_SERVER }}"
          echo "Hello World" >schema-changes.sql

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        id: upload-artifact
        with:
          name: delta-script-${{ matrix.environment }}
          path: schema-changes.sql

      - name: Post artifact link as comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |           
            const artifactUrl = `${{ steps.upload-artifact.outputs.artifact-url }}`;
            const commentBody = `The generated file [schema-changes.sql](${artifactUrl}) is available as an artifact.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            });          

  publish_stg:    
      if: github.event.pull_request.merged == true
      uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
      with:
        environment: approval-dev
  
  publish_dev:
    needs: publish_stg
    if: github.event.pull_request.merged == true && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev      

  publish_qa:
    needs: publish_dev
    if: github.event.pull_request.merged == true && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev

  publish_prd:
    needs: publish_qa
    if: github.event.pull_request.merged == true && always()
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: approval-dev
