name: build-push-deploy

on:
  workflow_dispatch:
jobs:
  create_image_tag:  
    strategy:
      matrix:
        env: ['dev', 'test', 'prod']  
      max-parallel: 1
    environment: ${{ matrix.env }}        
    runs-on: ubuntu-latest
    outputs:      
        IMAGE_TAG: ${{ steps.set_image_tag.outputs.IMAGE_TAG }}
    steps: 
      - name: Set image tag
        id: set_image_tag
        run: |
          echo "IMAGE_TAG=$(date -u +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo ${{ matrix.env }}


