name: Deploy 
on:
  pull_request:
    branches:
      - main  
    types: [opened, reopened, synchronize, closed]

jobs:
  build:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    strategy:
          matrix:
            profile_environment: ['dev', 'qa', 'prd']          
    environment: ${{ matrix.profile_environment }}      
    steps:        
      - name: Build
        run: |
          echo "build"          
  
  publish:    
    if: github.event.pull_request.merged == true
    strategy:
          matrix:
            profile_environment: ['dev', 'qa', 'prd']
    max-parallel: 1
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: ${{ matrix.profile_environment }}       
