name: build-push-deploy
on:
  workflow_dispatch:
jobs:
  build:    
    uses: kukrejaravi9/test-repo/.github/workflows/main_angular-php-test.yml@main
    with:      
      ENV_NAME: 'Hello World'
    secrets: inherit
    permissions:
      contents: write
