name: Build and Deploy - Production
run-name: Deploy to ${{ inputs.runner }}
on:
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: string

  workflow_call:
    inputs:
      some_input:
        description: 'Some input description'
        required: true 
        type: string
jobs:
  test2:
    runs-on: ubuntu-latest
    steps:    
        
    - name: Get triggering user name
      id: triggered-by      
      run: |
        echo hello world

       
