name: Deploy 
on:
  pull_request:
    branches:
      - main  
    types: [opened, reopened]

jobs:
  delete-and-create-dev-branch:
    runs-on: ubuntu-latest      
    steps:        
      - name: Delete current DEV branch
        run: |
          echo "Hello World"
