name: Build and Deploy - Production
run-name: Deploy to ${{ inputs.runner }}
on:
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: choice
        options: 
          - 'Option 1'
          
  schedule:    
    - cron:  '* * * * *'

env:
  DEFAULT_SOURCE: 'TEST'
  DEFAULT_DESTINATION: 'PROD'

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:    
        
    - name: Get triggering user name
      id: triggered-by      
      run: |
        echo ${{ inputs.some_input }} || ${{ env.DEFAULT_SOURCE }}
        echo ${{ inputs.some_input }} || ${{ env.DEFAULT_DESTINATION }}

       
