name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    strategy:
          matrix:
            profile_environment: ['dev', 'test', 'prod']
          max-parallel: 1
    environment: ${{ matrix.profile_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set latest_tag variable
        run: |
          latest_tag="9.11.1"  # Set latest_tag variable here        
      
      - name: Set latest_tag variable 1
        run: |          
          yq eval '(.images[] | select(.name == "ghcr.io/actions/gha-runner-scale-set-controller") | .newTag) =  env(latest_tag)' -i mynewfile.yml

          cat  mynewfile.yml
        shell: bash
          
