name: Build and Deploy - Production
run-name: ${{ inputs.some_input || 'macos-latest' }} to ${{ inputs.some_input || 'macos-latest' }}
on:
  schedule:
    - cron: '*/6 * * * *'
  
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: choice
        options: 
          - 'ubuntu-latest'

env:
  DEFAULT_SOURCE: 'macos-latest'  

jobs:
  test2: 
    strategy: 
      matrix:
        runner: [ubuntu-latest, macos-latest]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - name: print hello world
        run: echo hello world
      
     

       
