name: Build and Deploy - Production
on:
  #schedule:
    #- cron: '*/6 * * * *'
  
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: choice
        options: 
          - 'ubuntu-latest'
      some:
        description: 'Some input'
        required: true
        type: choice
        options: 
          - 'DEV'          
          - 'PROD'
          - 'TEST'

jobs:
  test2: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Set environment for script
      run: echo ${{ github.sha }}
          
      
     

       
