name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    environment: stg
    env:
      CURRENT_ENVIRONMENT: ${{ job.environment }}  # Set the environment variable    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag from ghcr.io
        id: get-latest-tag
        run: |          
          current_environment="${{ env.CURRENT_ENVIRONMENT }}"
          echo "Current Environment: $current_environment"
          
