name: Build and Deploy - Production
run-name: Deploy to ${{ inputs.runner }}
on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        description: Select the runner
        default: '1'
        options:
          - '1'
          - '2'      

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:    
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: kukrejaravi9/rebase-test
        ref: 'main'
        token: ${{ secrets.GH_PAT }}
        
    - name: Get triggering user name
      id: triggered-by
      if: always()
      run: |
        ls
        cat myfile.txt

       
