name: Build and Deploy - Production
on:    
  workflow_dispatch:
    inputs:
      import-destination:
        description: 'Some input'
        required: true
        type: choice
        options: 
          - 'DEV'          
          - 'PROD'
          - 'TEST'       

  schedule: 
    - cron: '* * * * *'

jobs:
  call-reusable-job: 
    runs-on: ubuntu-latest
    steps:    
    - name: Create github app token 
      env:
        import-destination: ${{ inputs.import-destination }}
      run: node myscript.js
      
