name: Build and Deploy - Production
on:    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Some input'
        required: true
        type: choice
        options: 
          - 'DEV'          
          - 'PROD'
          - 'TEST'

jobs:
  call-reusable-job: 
    uses: kukrejaravi9/TestRepo/.github/workflows/reusable-deploy-to-server.yml@main
    with:
      environment: ${{ inputs.environment || 'PROD' }}
      set-environment: ${{ github.event_name == 'schedule' && 'false' || 'true' }}
    secrets: inherit
