name: Get Latest Image Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    strategy:
          matrix:
            profile_environment: ['dev', 'test', 'prod']
          max-parallel: 1
    environment: ${{ matrix.profile_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag from ghcr.io
        id: get-latest-tag
        env:
          latest_tag: "1.11.999"
        run: |
          latest_tag="1.11.999"
          yq eval '(.images[] | select(.name == "ghcr.io/actions/gha-runner-scale-set-controller") | .newTag) =  strenv(latest_tag)' -i mynewfile.yml
          
