name: Deploy 
on:
  pull_request:
    branches:
      - main  
    types: [opened, reopened, synchronize, closed]

jobs:
  build:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest      
    steps:        
      - name: Build
        run: |
          echo "build"

  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest      
    steps:        
      - name: Publish
        run: |
          echo "Publish"
