name: Example Workflow

on: [push]

jobs:
  my_job_one:    
    if: ${{ always() }}
    runs-on: ubuntu-latest
    outputs:
      WORKFLOW_CANCELLED: ${{ steps.test-step-two.outputs.WORKFLOW_CANCELLED }}
    steps:      

      - name: Dummy
        id: test-step-two
        run: |
          echo "WORKFLOW_CANCELLED=true" >> GITHUB_OUTPUT

      - name: Is cancelled
        if: steps.test-step-two.outputs.WORKFLOW_CANCELLED == 'true'
        run: echo "cancelled() == true"        
        
