name: My Test

on:
  workflow_dispatch:

jobs:
  my-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Process images
        id: process_images
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          echo "hello world" >> hello.txt

      - name: Commit changes
        run: |          
            echo "-------------------------Commiting code-----------------------------------------"            
            git add .
            git commit -m "Updated manifest"
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              git checkout -b update-manifest-${{ github.run_id }}
              git push origin update-manifest-${{ github.run_id }}
            else
              git push
            fi 
          
