name: Pull Request Workflow
on:
  pull_request:
    types:
      [opened, closed]
      
jobs:
  get-next-android-versioncode:    
    uses: ./.github/workflows/reusable-test.yml

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: startsWith(github.base_ref, 'release-') || startsWith(github.base_ref, 'hotfix-')
    
    needs: get-next-android-versioncode
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: print
        run: |
          echo "Pull Request Branch: ${{ github.base_ref }}"
          echo "Pull Request Branch: ${{ github.head_ref }}"
          echo ${{ needs.get-next-android-versioncode.outputs.version_code }}
          
      - name: Extract version name from branch
        run: |
          if [ ${{ contains(github.base_ref, 'release-') }} = true ]; then
            SEPARATOR='release-' 
          elif [ ${{ contains(github.base_ref, 'hotfix-') }} = true ]; then
            SEPARATOR='hotfix-' 
          fi        
          echo "VERSION_NAME="${GITHUB_BASE_REF#"$SEPARATOR"}"" >> "$GITHUB_ENV"       
      
      - name: Print the version
        run: |
          echo ${{ env.VERSION_NAME }}            
