name: Deploy to server
on: 
  workflow_dispatch:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: string    
jobs: 
  wait_for_approval:    
    uses: kukrejaravi9/TestRepo/.github/workflows/deploy-to-production.yml@main
    with: 
      some_input: ${{ inputs.some_input }}
  
