name: Deploy to server
on: 
  workflow_dispatch 
jobs: 
  wait_for_approval:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: echo input
        id: test-step
        run: 
          chmod +x ./mytestscript.sh
          bash mytestscript.sh

      - name: print outouts
        run:
          echo ${{ steps.test-step.outputs.MY_CALL_ONE }}
          echo ${{ steps.test-step.outputs.MY_CALL_TWO }}
          echo ${{ steps.test-step.outputs.MY_CALL_THREE }}
    
  
