name: Publish
on: 

  workflow_call:
    inputs:
      environment:      
        type: string
        required: false
    
jobs: 
  wait_for_approval:    
    runs-on: ubuntu-latest      
    environment: approve 
    steps:
    - name: Approval
      id: set-output
      run: |
        echo 'Aproval'        
    
  publish:
    needs: [wait_for_approval]
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      id: set-output
      run: |
        echo 'Publish' 
    
    
  
