name: Deploy to server
on: 
  workflow_call:
    inputs:
      some_input:
        description: 'Some input description'
        required: true
        type: string    
jobs: 
  wait_for_approval:    
    runs-on: ["${{ inputs.some_input }}"]
    steps:
      - name: echo input
        run: 
          echo ${{ inputs.some_input }}
    
  
