name: Deploy to server
on: 
  workflow_dispatch:
    inputs:
      environment:      
        type: choice
        required: true
        options:
          - 'PROD'
          - 'TEST'

  workflow_call:
    inputs:
      environment:
        type: string
      set-environment:
        type: string
    
jobs: 
  reusable-job:
    environment: ${{ inputs.set-environment != 'false' && inputs.environment || '' }}
    runs-on: ubuntu-latest
    steps:
      
      - name: echo input
        id: test-step
        run: echo "reusable job"
    
    
  
