name: Publish schema changes
on: 
  workflow_call:
    inputs:
      environment:      
        type: string
        required: false

concurrency:
  group: schema_update_automation
  cancel-in-progress: true
  
jobs:        
  publish_changes:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2   
        
    - name: Publish schema changes
      run: |
        echo "Hello World"
