name: Deploy to server
on: 
  workflow_dispatch:
    inputs:
      environment:      
        type: string
        required: false
    
jobs: 
  reusable-job:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:      
      - name: echo input
        id: test-step
        run: echo "reusable job"
    
    
  
