name: Publish schema changes
on: 
  workflow_call:
    inputs:
      environment:      
        type: string
        required: false    
jobs:        
  publish_changes:
    runs-on: cloud-runners-ads
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2   
        
    - name: Publish schema changes
      run: |
        echo "Hello World"
