name: Deploy to server
on: 
  workflow_dispatch:
    inputs:
      import_destination:      
        type: choice
        required: true
        options:
          - 'PROD'
          - 'TEST'
    
jobs: 
  wait_for_approval:    
    runs-on: [ubuntu-latest, "${{ inputs.import_destination || 'PROD'  }}", "${{ inputs.import_destination == 'PROD' && 'pend01' ||  inputs.import_destination }}", "${{ inputs.import_destination || 'pend01'  }}" ]
    steps:
      - uses: actions/checkout@v4
      
      - name: echo input
        id: test-step
        run: 
          #chmod +x ./mytestscript.sh
          bash mytestscript.sh

      - name: print outouts
        run:
          echo "Printing Outputs"
          echo  ${{ steps.test-step.outputs.MY_CALL_ONE }}
          echo ${{ steps.test-step.outputs.MY_CALL_TWO }}
          echo ${{ steps.test-step.outputs.MY_CALL_THREE }}
    
  
