name: test-user-details

on:
  workflow_dispatch:
  
jobs: 
  test-user-details:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    
    - name: print user details
      run: |
        echo ${{ github.actor }}
