name: test-user-details

on:
  workflow_dispatch:
  
jobs: 
  test-user-details:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    
    - name: print user details
      run: |
        echo ${{ github.actor }}
        
    - name: Get User Details
      run: |
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/users/${{ github.actor }}")
        firstName=$(echo "$response" | jq -r '.name // empty' | cut -d " " -f 1)
        lastName=$(echo "$response" | jq -r '.name // empty' | cut -d " " -f 2)
        echo "First Name: $firstName"
        echo "Last Name: $lastName"
        
